### ISSUE TITLE
Registry returned 404 for GET on https://registry.npmjs.org/jquery-asPieProgress

### ISSUE THREAD

**Issue by FDiskas** [amazingSurge/jquery-asPieProgress#12]
Please register this in npm repozitory

**Comment by amazingSurge** [comment]
OK. We will do it soon.

**Comment by FDiskas** [comment]
Waiting...

**Comment by FDiskas** [comment]
Can't wait so long - published by my self.

**Comment by FDiskas** [comment]
:weary: contact me then you will be ready. I will forward the ownership to you

**Comment by FDiskas** [comment]
the same problem are on other plugins

**Comment by amazingSurge** [comment]
sorry for the delay. We are working on upgrade the codes. We are still not decide using jquery-asPieProgress as name that register on npm as we didn't like `as` in the name. Did you have any suggestion?

**Comment by FDiskas** [comment]
```jquery-sPieProgress``` or ```jquery-aPieProgress```
I suggest you just remove one letter from ```as```

**Comment by amazingSurge** [comment]
@FDiskas 

Can you transfer the package to me?

We will use the same name at the moment after discuss with our team.

Thank you!

**Comment by FDiskas** [comment]
Did you registered on https://www.npmjs.com ?

**Comment by amazingSurge** [comment]
yes. the same name.

**Comment by FDiskas** [comment]
https://www.npmjs.com/~amazingSurge 404
Please post exactly your user name - need to specify the username in command
```
npm owner add @amazingSurge jquery-asPieProgress
```

**Comment by FDiskas** [comment]
Oh sorry lowercased

**Comment by FDiskas** [comment]
https://www.npmjs.com/~amazingsurge - transfared

**Comment by FDiskas** [comment]
More info here
https://docs.npmjs.com/cli/owner
you can remove me from owner list if you wish

**Comment by amazingSurge** [comment]
thankyou！

**Comment by FDiskas** [comment]
For easy release of new version i sugesst you to try this 
https://www.npmjs.com/package/npm-release
this will increment version, create a tag in git and publish new release on github and npmjs registry
with one command

**Comment by amazingSurge** [comment]
Lookings awesome!
