### ISSUE TITLE
IE11 does not refresh path after changing d attr

### ISSUE THREAD

**Issue by zsakmany** [amazingSurge/jquery-asPieProgress#5]
We use the chart to represent how much time you have left in a quiz. There is a timer in the content div. As the progressBar grows, the content div covers the path.
I managed to make it work, by changing the logic you drew the line. Instead of changing the strokeDashoffset, I increment the first part of the strokeDasharray.
            this.bar.style.strokeDasharray = (length-offset) + " " + length;
//            this.bar.style.strokeDashoffset = offset;
            this.bar.style.strokeDashoffset = 0;
Hope it'll help!
Thanks the plugin!
![aspieprogressbug](https://cloud.githubusercontent.com/assets/7439791/6486736/32051cc6-c28d-11e4-8608-7f695fa9506c.jpg)

**Comment by amazingSurge** [comment]
hello, I just add time count down support. Please update your lib and check the example.

Regards.

**Comment by zsakmany** [comment]
The problem is gone, and IE does refreshes the path. The end of the line still looks and acts weird, but it is better! Looks good in Chrome: 40.0.2214.115 m

**Comment by amazingSurge** [comment]
Thanks for the response. I will check ie later.
