### ISSUE TITLE
Spinner Going reverse by following the step bellow

### ISSUE THREAD

**Issue by binoy14** [amazingSurge/jquery-asPieProgress#6]
Start the demo, click start and go to a new tab wait for few seconds and come back to the demo and then the spinner goes in reverse and negative numbers. Let me if you want a screen recording to see the issue. 
![screenshot at apr 28 17-37-25](https://cloud.githubusercontent.com/assets/6476108/7381039/d52f2f5c-edcd-11e4-936b-eaddd1360a9b.png)

**Comment by amazingSurge** [comment]
Hi, which browse do you used?

**Comment by binoy14** [comment]
This happens on Chrome, Firefox and Safari latest. Did not get a chance to test it on IE

**Comment by amazingSurge** [comment]
Can you make a screen recording? It's working fine on my test. So i didn't know what happens.

**Comment by binoy14** [comment]
Steps to recreate
1) Start the spinner
2) Before the spinner goes to 100% switch to a new tab, wait for 4 -5 seconds. 
3) go back to the spinner tab and it starts going in reverse and negative. 

[Video](http://youtu.be/zjFjqTRMPK4)

**Comment by amazingSurge** [comment]
looks funny. :D  I am working on it. It will be fixed soon. Thanks!
