### ISSUE TITLE
iOS issue

### ISSUE THREAD

**Issue by sanjukanwasi** [amazingSurge/jquery-asPieProgress#9]
loader percentage is not working on iOs...Iphone 5 and 6 Safari browser.

**Comment by kows** [comment]
I had a similar issue on iPads with iOS 8.
Counter went from minus some high number to 0.
Adding 8 to following line fixed it for me:
if (/iP(ad|hone|od).*OS (6|7)/.test(window.navigator.userAgent) // iOS6 is buggy
